Search.appendIndex(
    [
                {
            "fqsen": "\\App\\Controller\\MediaController",
            "name": "MediaController",
            "summary": "",
            "url": "classes/App-Controller-MediaController.html"
        },                {
            "fqsen": "\\App\\Controller\\MediaController\u003A\u003AeditPicture\u0028\u0029",
            "name": "editPicture",
            "summary": "Edit\u0020a\u0020picture\u0020object",
            "url": "classes/App-Controller-MediaController.html#method_editPicture"
        },                {
            "fqsen": "\\App\\Controller\\MediaController\u003A\u003AdeletePicture\u0028\u0029",
            "name": "deletePicture",
            "summary": "Delete\u0020a\u0020Picture\u0020from\u0020the\u0020database",
            "url": "classes/App-Controller-MediaController.html#method_deletePicture"
        },                {
            "fqsen": "\\App\\Controller\\MediaController\u003A\u003AeditVideo\u0028\u0029",
            "name": "editVideo",
            "summary": "Edit\u0020a\u0020video\u0020object",
            "url": "classes/App-Controller-MediaController.html#method_editVideo"
        },                {
            "fqsen": "\\App\\Controller\\MediaController\u003A\u003AdeleteVideo\u0028\u0029",
            "name": "deleteVideo",
            "summary": "Delete\u0020a\u0020Video\u0020from\u0020the\u0020database",
            "url": "classes/App-Controller-MediaController.html#method_deleteVideo"
        },                {
            "fqsen": "\\App\\Controller\\SecurityController",
            "name": "SecurityController",
            "summary": "",
            "url": "classes/App-Controller-SecurityController.html"
        },                {
            "fqsen": "\\App\\Controller\\SecurityController\u003A\u003Alogin\u0028\u0029",
            "name": "login",
            "summary": "Displays\u0020login\u0020form\u0020and\u0020provides\u0020access\u0020to\u0020user\u0027s\u0020account",
            "url": "classes/App-Controller-SecurityController.html#method_login"
        },                {
            "fqsen": "\\App\\Controller\\SecurityController\u003A\u003Alogout\u0028\u0029",
            "name": "logout",
            "summary": "Logout\u0020the\u0020user\u0020session",
            "url": "classes/App-Controller-SecurityController.html#method_logout"
        },                {
            "fqsen": "\\App\\Controller\\UserController",
            "name": "UserController",
            "summary": "Provides\u0020common\u0020features\u0020needed\u0020for\u0020User\u0020management.",
            "url": "classes/App-Controller-UserController.html"
        },                {
            "fqsen": "\\App\\Controller\\UserController\u003A\u003Aregistration\u0028\u0029",
            "name": "registration",
            "summary": "Creates",
            "url": "classes/App-Controller-UserController.html#method_registration"
        },                {
            "fqsen": "\\App\\Controller\\UserController\u003A\u003AcheckRegistration\u0028\u0029",
            "name": "checkRegistration",
            "summary": "Validates\u0020registration\u0020with\u0020email\u0020confirmation",
            "url": "classes/App-Controller-UserController.html#method_checkRegistration"
        },                {
            "fqsen": "\\App\\Controller\\UserController\u003A\u003Aprofile\u0028\u0029",
            "name": "profile",
            "summary": "Provides\u0020the\u0020form\u0020to\u0020change\u0020information\u0020on\u0020user\u0027s\u0020account",
            "url": "classes/App-Controller-UserController.html#method_profile"
        },                {
            "fqsen": "\\App\\Controller\\UserController\u003A\u003AresetPassword\u0028\u0029",
            "name": "resetPassword",
            "summary": "Provides\u0020form\u0020to\u0020create\u0020a\u0020new\u0020password",
            "url": "classes/App-Controller-UserController.html#method_resetPassword"
        },                {
            "fqsen": "\\App\\Controller\\UserController\u003A\u003AforgotPassword\u0028\u0029",
            "name": "forgotPassword",
            "summary": "Provides\u0020feature\u0020to\u0020change\u0020password\u0020for\u0020a\u0020user\u0020registered",
            "url": "classes/App-Controller-UserController.html#method_forgotPassword"
        },                {
            "fqsen": "\\App\\Controller\\UserController\u003A\u003ApasswordProcess\u0028\u0029",
            "name": "passwordProcess",
            "summary": "Provides\u0020feature\u0020to\u0020change\u0020password\u0020for\u0020user\u0020registered\u0020and\u0020authenticated",
            "url": "classes/App-Controller-UserController.html#method_passwordProcess"
        },                {
            "fqsen": "\\App\\DataFixtures\\AppFixtures",
            "name": "AppFixtures",
            "summary": "",
            "url": "classes/App-DataFixtures-AppFixtures.html"
        },                {
            "fqsen": "\\App\\DataFixtures\\AppFixtures\u003A\u003Aload\u0028\u0029",
            "name": "load",
            "summary": "",
            "url": "classes/App-DataFixtures-AppFixtures.html#method_load"
        },                {
            "fqsen": "\\App\\DataFixtures\\TrickFixtures",
            "name": "TrickFixtures",
            "summary": "",
            "url": "classes/App-DataFixtures-TrickFixtures.html"
        },                {
            "fqsen": "\\App\\DataFixtures\\TrickFixtures\u003A\u003Aload\u0028\u0029",
            "name": "load",
            "summary": "",
            "url": "classes/App-DataFixtures-TrickFixtures.html#method_load"
        },                {
            "fqsen": "\\App\\DataFixtures\\UserFixtures",
            "name": "UserFixtures",
            "summary": "",
            "url": "classes/App-DataFixtures-UserFixtures.html"
        },                {
            "fqsen": "\\App\\DataFixtures\\UserFixtures\u003A\u003Aload\u0028\u0029",
            "name": "load",
            "summary": "",
            "url": "classes/App-DataFixtures-UserFixtures.html#method_load"
        },                {
            "fqsen": "\\App\\Entity\\Category",
            "name": "Category",
            "summary": "Class\u0020represents\u0020a\u0020category",
            "url": "classes/App-Entity-Category.html"
        },                {
            "fqsen": "\\App\\Entity\\Category\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Entity-Category.html#method___construct"
        },                {
            "fqsen": "\\App\\Entity\\Category\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "classes/App-Entity-Category.html#method_getId"
        },                {
            "fqsen": "\\App\\Entity\\Category\u003A\u003AgetName\u0028\u0029",
            "name": "getName",
            "summary": "",
            "url": "classes/App-Entity-Category.html#method_getName"
        },                {
            "fqsen": "\\App\\Entity\\Category\u003A\u003AsetName\u0028\u0029",
            "name": "setName",
            "summary": "",
            "url": "classes/App-Entity-Category.html#method_setName"
        },                {
            "fqsen": "\\App\\Entity\\Category\u003A\u003AgetTricks\u0028\u0029",
            "name": "getTricks",
            "summary": "",
            "url": "classes/App-Entity-Category.html#method_getTricks"
        },                {
            "fqsen": "\\App\\Entity\\Category\u003A\u003AaddTrick\u0028\u0029",
            "name": "addTrick",
            "summary": "",
            "url": "classes/App-Entity-Category.html#method_addTrick"
        },                {
            "fqsen": "\\App\\Entity\\Category\u003A\u003AremoveTrick\u0028\u0029",
            "name": "removeTrick",
            "summary": "",
            "url": "classes/App-Entity-Category.html#method_removeTrick"
        },                {
            "fqsen": "\\App\\Entity\\Category\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/App-Entity-Category.html#property_id"
        },                {
            "fqsen": "\\App\\Entity\\Category\u003A\u003A\u0024name",
            "name": "name",
            "summary": "",
            "url": "classes/App-Entity-Category.html#property_name"
        },                {
            "fqsen": "\\App\\Entity\\Category\u003A\u003A\u0024tricks",
            "name": "tricks",
            "summary": "",
            "url": "classes/App-Entity-Category.html#property_tricks"
        },                {
            "fqsen": "\\App\\Entity\\Comment",
            "name": "Comment",
            "summary": "",
            "url": "classes/App-Entity-Comment.html"
        },                {
            "fqsen": "\\App\\Entity\\Comment\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "classes/App-Entity-Comment.html#method_getId"
        },                {
            "fqsen": "\\App\\Entity\\Comment\u003A\u003AgetCreationDate\u0028\u0029",
            "name": "getCreationDate",
            "summary": "",
            "url": "classes/App-Entity-Comment.html#method_getCreationDate"
        },                {
            "fqsen": "\\App\\Entity\\Comment\u003A\u003AsetCreationDate\u0028\u0029",
            "name": "setCreationDate",
            "summary": "",
            "url": "classes/App-Entity-Comment.html#method_setCreationDate"
        },                {
            "fqsen": "\\App\\Entity\\Comment\u003A\u003AgetContent\u0028\u0029",
            "name": "getContent",
            "summary": "",
            "url": "classes/App-Entity-Comment.html#method_getContent"
        },                {
            "fqsen": "\\App\\Entity\\Comment\u003A\u003AsetContent\u0028\u0029",
            "name": "setContent",
            "summary": "",
            "url": "classes/App-Entity-Comment.html#method_setContent"
        },                {
            "fqsen": "\\App\\Entity\\Comment\u003A\u003AgetTricks\u0028\u0029",
            "name": "getTricks",
            "summary": "",
            "url": "classes/App-Entity-Comment.html#method_getTricks"
        },                {
            "fqsen": "\\App\\Entity\\Comment\u003A\u003AsetTricks\u0028\u0029",
            "name": "setTricks",
            "summary": "",
            "url": "classes/App-Entity-Comment.html#method_setTricks"
        },                {
            "fqsen": "\\App\\Entity\\Comment\u003A\u003AgetUser\u0028\u0029",
            "name": "getUser",
            "summary": "",
            "url": "classes/App-Entity-Comment.html#method_getUser"
        },                {
            "fqsen": "\\App\\Entity\\Comment\u003A\u003AsetUser\u0028\u0029",
            "name": "setUser",
            "summary": "",
            "url": "classes/App-Entity-Comment.html#method_setUser"
        },                {
            "fqsen": "\\App\\Entity\\Comment\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/App-Entity-Comment.html#property_id"
        },                {
            "fqsen": "\\App\\Entity\\Comment\u003A\u003A\u0024creationDate",
            "name": "creationDate",
            "summary": "",
            "url": "classes/App-Entity-Comment.html#property_creationDate"
        },                {
            "fqsen": "\\App\\Entity\\Comment\u003A\u003A\u0024content",
            "name": "content",
            "summary": "",
            "url": "classes/App-Entity-Comment.html#property_content"
        },                {
            "fqsen": "\\App\\Entity\\Comment\u003A\u003A\u0024tricks",
            "name": "tricks",
            "summary": "",
            "url": "classes/App-Entity-Comment.html#property_tricks"
        },                {
            "fqsen": "\\App\\Entity\\Comment\u003A\u003A\u0024user",
            "name": "user",
            "summary": "",
            "url": "classes/App-Entity-Comment.html#property_user"
        },                {
            "fqsen": "\\App\\Entity\\Picture",
            "name": "Picture",
            "summary": "",
            "url": "classes/App-Entity-Picture.html"
        },                {
            "fqsen": "\\App\\Entity\\Picture\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "classes/App-Entity-Picture.html#method_getId"
        },                {
            "fqsen": "\\App\\Entity\\Picture\u003A\u003AgetTitle\u0028\u0029",
            "name": "getTitle",
            "summary": "",
            "url": "classes/App-Entity-Picture.html#method_getTitle"
        },                {
            "fqsen": "\\App\\Entity\\Picture\u003A\u003AsetTitle\u0028\u0029",
            "name": "setTitle",
            "summary": "",
            "url": "classes/App-Entity-Picture.html#method_setTitle"
        },                {
            "fqsen": "\\App\\Entity\\Picture\u003A\u003AgetFileName\u0028\u0029",
            "name": "getFileName",
            "summary": "",
            "url": "classes/App-Entity-Picture.html#method_getFileName"
        },                {
            "fqsen": "\\App\\Entity\\Picture\u003A\u003AsetFileName\u0028\u0029",
            "name": "setFileName",
            "summary": "",
            "url": "classes/App-Entity-Picture.html#method_setFileName"
        },                {
            "fqsen": "\\App\\Entity\\Picture\u003A\u003AgetTricks\u0028\u0029",
            "name": "getTricks",
            "summary": "",
            "url": "classes/App-Entity-Picture.html#method_getTricks"
        },                {
            "fqsen": "\\App\\Entity\\Picture\u003A\u003AsetTricks\u0028\u0029",
            "name": "setTricks",
            "summary": "",
            "url": "classes/App-Entity-Picture.html#method_setTricks"
        },                {
            "fqsen": "\\App\\Entity\\Picture\u003A\u003AgetFile\u0028\u0029",
            "name": "getFile",
            "summary": "",
            "url": "classes/App-Entity-Picture.html#method_getFile"
        },                {
            "fqsen": "\\App\\Entity\\Picture\u003A\u003AsetFile\u0028\u0029",
            "name": "setFile",
            "summary": "",
            "url": "classes/App-Entity-Picture.html#method_setFile"
        },                {
            "fqsen": "\\App\\Entity\\Picture\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/App-Entity-Picture.html#property_id"
        },                {
            "fqsen": "\\App\\Entity\\Picture\u003A\u003A\u0024title",
            "name": "title",
            "summary": "",
            "url": "classes/App-Entity-Picture.html#property_title"
        },                {
            "fqsen": "\\App\\Entity\\Picture\u003A\u003A\u0024fileName",
            "name": "fileName",
            "summary": "",
            "url": "classes/App-Entity-Picture.html#property_fileName"
        },                {
            "fqsen": "\\App\\Entity\\Picture\u003A\u003A\u0024tricks",
            "name": "tricks",
            "summary": "",
            "url": "classes/App-Entity-Picture.html#property_tricks"
        },                {
            "fqsen": "\\App\\Entity\\Picture\u003A\u003A\u0024file",
            "name": "file",
            "summary": "",
            "url": "classes/App-Entity-Picture.html#property_file"
        },                {
            "fqsen": "\\App\\Entity\\Trick",
            "name": "Trick",
            "summary": "",
            "url": "classes/App-Entity-Trick.html"
        },                {
            "fqsen": "\\App\\Entity\\Trick\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Entity-Trick.html#method___construct"
        },                {
            "fqsen": "\\App\\Entity\\Trick\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "classes/App-Entity-Trick.html#method_getId"
        },                {
            "fqsen": "\\App\\Entity\\Trick\u003A\u003AgetName\u0028\u0029",
            "name": "getName",
            "summary": "",
            "url": "classes/App-Entity-Trick.html#method_getName"
        },                {
            "fqsen": "\\App\\Entity\\Trick\u003A\u003AsetName\u0028\u0029",
            "name": "setName",
            "summary": "",
            "url": "classes/App-Entity-Trick.html#method_setName"
        },                {
            "fqsen": "\\App\\Entity\\Trick\u003A\u003AgetDescription\u0028\u0029",
            "name": "getDescription",
            "summary": "",
            "url": "classes/App-Entity-Trick.html#method_getDescription"
        },                {
            "fqsen": "\\App\\Entity\\Trick\u003A\u003AsetDescription\u0028\u0029",
            "name": "setDescription",
            "summary": "",
            "url": "classes/App-Entity-Trick.html#method_setDescription"
        },                {
            "fqsen": "\\App\\Entity\\Trick\u003A\u003AgetCreationDate\u0028\u0029",
            "name": "getCreationDate",
            "summary": "",
            "url": "classes/App-Entity-Trick.html#method_getCreationDate"
        },                {
            "fqsen": "\\App\\Entity\\Trick\u003A\u003AsetCreationDate\u0028\u0029",
            "name": "setCreationDate",
            "summary": "",
            "url": "classes/App-Entity-Trick.html#method_setCreationDate"
        },                {
            "fqsen": "\\App\\Entity\\Trick\u003A\u003AgetModificationDate\u0028\u0029",
            "name": "getModificationDate",
            "summary": "",
            "url": "classes/App-Entity-Trick.html#method_getModificationDate"
        },                {
            "fqsen": "\\App\\Entity\\Trick\u003A\u003AsetModificationDate\u0028\u0029",
            "name": "setModificationDate",
            "summary": "",
            "url": "classes/App-Entity-Trick.html#method_setModificationDate"
        },                {
            "fqsen": "\\App\\Entity\\Trick\u003A\u003AgetMainPicture\u0028\u0029",
            "name": "getMainPicture",
            "summary": "",
            "url": "classes/App-Entity-Trick.html#method_getMainPicture"
        },                {
            "fqsen": "\\App\\Entity\\Trick\u003A\u003AsetMainPicture\u0028\u0029",
            "name": "setMainPicture",
            "summary": "",
            "url": "classes/App-Entity-Trick.html#method_setMainPicture"
        },                {
            "fqsen": "\\App\\Entity\\Trick\u003A\u003AgetFileMainPicture\u0028\u0029",
            "name": "getFileMainPicture",
            "summary": "",
            "url": "classes/App-Entity-Trick.html#method_getFileMainPicture"
        },                {
            "fqsen": "\\App\\Entity\\Trick\u003A\u003AsetFileMainPicture\u0028\u0029",
            "name": "setFileMainPicture",
            "summary": "",
            "url": "classes/App-Entity-Trick.html#method_setFileMainPicture"
        },                {
            "fqsen": "\\App\\Entity\\Trick\u003A\u003AgetCategory\u0028\u0029",
            "name": "getCategory",
            "summary": "",
            "url": "classes/App-Entity-Trick.html#method_getCategory"
        },                {
            "fqsen": "\\App\\Entity\\Trick\u003A\u003AsetCategory\u0028\u0029",
            "name": "setCategory",
            "summary": "",
            "url": "classes/App-Entity-Trick.html#method_setCategory"
        },                {
            "fqsen": "\\App\\Entity\\Trick\u003A\u003AgetComments\u0028\u0029",
            "name": "getComments",
            "summary": "",
            "url": "classes/App-Entity-Trick.html#method_getComments"
        },                {
            "fqsen": "\\App\\Entity\\Trick\u003A\u003AaddComment\u0028\u0029",
            "name": "addComment",
            "summary": "",
            "url": "classes/App-Entity-Trick.html#method_addComment"
        },                {
            "fqsen": "\\App\\Entity\\Trick\u003A\u003AremoveComment\u0028\u0029",
            "name": "removeComment",
            "summary": "",
            "url": "classes/App-Entity-Trick.html#method_removeComment"
        },                {
            "fqsen": "\\App\\Entity\\Trick\u003A\u003AgetUser\u0028\u0029",
            "name": "getUser",
            "summary": "",
            "url": "classes/App-Entity-Trick.html#method_getUser"
        },                {
            "fqsen": "\\App\\Entity\\Trick\u003A\u003AsetUser\u0028\u0029",
            "name": "setUser",
            "summary": "",
            "url": "classes/App-Entity-Trick.html#method_setUser"
        },                {
            "fqsen": "\\App\\Entity\\Trick\u003A\u003AgetPictures\u0028\u0029",
            "name": "getPictures",
            "summary": "",
            "url": "classes/App-Entity-Trick.html#method_getPictures"
        },                {
            "fqsen": "\\App\\Entity\\Trick\u003A\u003AaddPicture\u0028\u0029",
            "name": "addPicture",
            "summary": "",
            "url": "classes/App-Entity-Trick.html#method_addPicture"
        },                {
            "fqsen": "\\App\\Entity\\Trick\u003A\u003AremovePicture\u0028\u0029",
            "name": "removePicture",
            "summary": "",
            "url": "classes/App-Entity-Trick.html#method_removePicture"
        },                {
            "fqsen": "\\App\\Entity\\Trick\u003A\u003AgetVideos\u0028\u0029",
            "name": "getVideos",
            "summary": "",
            "url": "classes/App-Entity-Trick.html#method_getVideos"
        },                {
            "fqsen": "\\App\\Entity\\Trick\u003A\u003AaddVideo\u0028\u0029",
            "name": "addVideo",
            "summary": "",
            "url": "classes/App-Entity-Trick.html#method_addVideo"
        },                {
            "fqsen": "\\App\\Entity\\Trick\u003A\u003AremoveVideo\u0028\u0029",
            "name": "removeVideo",
            "summary": "",
            "url": "classes/App-Entity-Trick.html#method_removeVideo"
        },                {
            "fqsen": "\\App\\Entity\\Trick\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/App-Entity-Trick.html#property_id"
        },                {
            "fqsen": "\\App\\Entity\\Trick\u003A\u003A\u0024name",
            "name": "name",
            "summary": "",
            "url": "classes/App-Entity-Trick.html#property_name"
        },                {
            "fqsen": "\\App\\Entity\\Trick\u003A\u003A\u0024description",
            "name": "description",
            "summary": "",
            "url": "classes/App-Entity-Trick.html#property_description"
        },                {
            "fqsen": "\\App\\Entity\\Trick\u003A\u003A\u0024creationDate",
            "name": "creationDate",
            "summary": "",
            "url": "classes/App-Entity-Trick.html#property_creationDate"
        },                {
            "fqsen": "\\App\\Entity\\Trick\u003A\u003A\u0024modificationDate",
            "name": "modificationDate",
            "summary": "",
            "url": "classes/App-Entity-Trick.html#property_modificationDate"
        },                {
            "fqsen": "\\App\\Entity\\Trick\u003A\u003A\u0024mainPicture",
            "name": "mainPicture",
            "summary": "",
            "url": "classes/App-Entity-Trick.html#property_mainPicture"
        },                {
            "fqsen": "\\App\\Entity\\Trick\u003A\u003A\u0024fileMainPicture",
            "name": "fileMainPicture",
            "summary": "",
            "url": "classes/App-Entity-Trick.html#property_fileMainPicture"
        },                {
            "fqsen": "\\App\\Entity\\Trick\u003A\u003A\u0024category",
            "name": "category",
            "summary": "",
            "url": "classes/App-Entity-Trick.html#property_category"
        },                {
            "fqsen": "\\App\\Entity\\Trick\u003A\u003A\u0024comments",
            "name": "comments",
            "summary": "",
            "url": "classes/App-Entity-Trick.html#property_comments"
        },                {
            "fqsen": "\\App\\Entity\\Trick\u003A\u003A\u0024user",
            "name": "user",
            "summary": "",
            "url": "classes/App-Entity-Trick.html#property_user"
        },                {
            "fqsen": "\\App\\Entity\\Trick\u003A\u003A\u0024pictures",
            "name": "pictures",
            "summary": "",
            "url": "classes/App-Entity-Trick.html#property_pictures"
        },                {
            "fqsen": "\\App\\Entity\\Trick\u003A\u003A\u0024videos",
            "name": "videos",
            "summary": "",
            "url": "classes/App-Entity-Trick.html#property_videos"
        },                {
            "fqsen": "\\App\\Entity\\User",
            "name": "User",
            "summary": "",
            "url": "classes/App-Entity-User.html"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Entity-User.html#method___construct"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_getId"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AgetLastName\u0028\u0029",
            "name": "getLastName",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_getLastName"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AsetLastName\u0028\u0029",
            "name": "setLastName",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_setLastName"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AgetFirstName\u0028\u0029",
            "name": "getFirstName",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_getFirstName"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AsetFirstName\u0028\u0029",
            "name": "setFirstName",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_setFirstName"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AgetUsername\u0028\u0029",
            "name": "getUsername",
            "summary": "Returns\u0020the\u0020username\u0020used\u0020to\u0020authenticate\u0020the\u0020user.",
            "url": "classes/App-Entity-User.html#method_getUsername"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AsetUsername\u0028\u0029",
            "name": "setUsername",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_setUsername"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AgetEmail\u0028\u0029",
            "name": "getEmail",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_getEmail"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AsetEmail\u0028\u0029",
            "name": "setEmail",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_setEmail"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AgetPassword\u0028\u0029",
            "name": "getPassword",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_getPassword"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AsetPassword\u0028\u0029",
            "name": "setPassword",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_setPassword"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AgetPhoto\u0028\u0029",
            "name": "getPhoto",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_getPhoto"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AsetPhoto\u0028\u0029",
            "name": "setPhoto",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_setPhoto"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AgetValidated\u0028\u0029",
            "name": "getValidated",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_getValidated"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AsetValidated\u0028\u0029",
            "name": "setValidated",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_setValidated"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AgetTricks\u0028\u0029",
            "name": "getTricks",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_getTricks"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AaddTrick\u0028\u0029",
            "name": "addTrick",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_addTrick"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AremoveTrick\u0028\u0029",
            "name": "removeTrick",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_removeTrick"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AgetComments\u0028\u0029",
            "name": "getComments",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_getComments"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AaddComment\u0028\u0029",
            "name": "addComment",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_addComment"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AremoveComment\u0028\u0029",
            "name": "removeComment",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_removeComment"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AgetRoles\u0028\u0029",
            "name": "getRoles",
            "summary": "Returns\u0020the\u0020roles\u0020granted\u0020to\u0020the\u0020user.",
            "url": "classes/App-Entity-User.html#method_getRoles"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AgetSalt\u0028\u0029",
            "name": "getSalt",
            "summary": "Returns\u0020the\u0020salt\u0020that\u0020was\u0020originally\u0020used\u0020to\u0020encode\u0020the\u0020password.",
            "url": "classes/App-Entity-User.html#method_getSalt"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AeraseCredentials\u0028\u0029",
            "name": "eraseCredentials",
            "summary": "Removes\u0020sensitive\u0020data\u0020from\u0020the\u0020user.",
            "url": "classes/App-Entity-User.html#method_eraseCredentials"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AgetApiToken\u0028\u0029",
            "name": "getApiToken",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_getApiToken"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AsetApiToken\u0028\u0029",
            "name": "setApiToken",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_setApiToken"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AgetFile\u0028\u0029",
            "name": "getFile",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_getFile"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AsetFile\u0028\u0029",
            "name": "setFile",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_setFile"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/App-Entity-User.html#property_id"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003A\u0024lastName",
            "name": "lastName",
            "summary": "",
            "url": "classes/App-Entity-User.html#property_lastName"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003A\u0024firstName",
            "name": "firstName",
            "summary": "",
            "url": "classes/App-Entity-User.html#property_firstName"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003A\u0024username",
            "name": "username",
            "summary": "",
            "url": "classes/App-Entity-User.html#property_username"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003A\u0024email",
            "name": "email",
            "summary": "",
            "url": "classes/App-Entity-User.html#property_email"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003A\u0024password",
            "name": "password",
            "summary": "",
            "url": "classes/App-Entity-User.html#property_password"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003A\u0024photo",
            "name": "photo",
            "summary": "",
            "url": "classes/App-Entity-User.html#property_photo"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003A\u0024validated",
            "name": "validated",
            "summary": "",
            "url": "classes/App-Entity-User.html#property_validated"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003A\u0024tricks",
            "name": "tricks",
            "summary": "",
            "url": "classes/App-Entity-User.html#property_tricks"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003A\u0024comments",
            "name": "comments",
            "summary": "",
            "url": "classes/App-Entity-User.html#property_comments"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003A\u0024apiToken",
            "name": "apiToken",
            "summary": "",
            "url": "classes/App-Entity-User.html#property_apiToken"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003A\u0024file",
            "name": "file",
            "summary": "",
            "url": "classes/App-Entity-User.html#property_file"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003A\u0024salt",
            "name": "salt",
            "summary": "",
            "url": "classes/App-Entity-User.html#property_salt"
        },                {
            "fqsen": "\\App\\Entity\\Video",
            "name": "Video",
            "summary": "",
            "url": "classes/App-Entity-Video.html"
        },                {
            "fqsen": "\\App\\Entity\\Video\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "classes/App-Entity-Video.html#method_getId"
        },                {
            "fqsen": "\\App\\Entity\\Video\u003A\u003AgetTitle\u0028\u0029",
            "name": "getTitle",
            "summary": "",
            "url": "classes/App-Entity-Video.html#method_getTitle"
        },                {
            "fqsen": "\\App\\Entity\\Video\u003A\u003AsetTitle\u0028\u0029",
            "name": "setTitle",
            "summary": "",
            "url": "classes/App-Entity-Video.html#method_setTitle"
        },                {
            "fqsen": "\\App\\Entity\\Video\u003A\u003AgetUrl\u0028\u0029",
            "name": "getUrl",
            "summary": "",
            "url": "classes/App-Entity-Video.html#method_getUrl"
        },                {
            "fqsen": "\\App\\Entity\\Video\u003A\u003AsetUrl\u0028\u0029",
            "name": "setUrl",
            "summary": "",
            "url": "classes/App-Entity-Video.html#method_setUrl"
        },                {
            "fqsen": "\\App\\Entity\\Video\u003A\u003AgetTricks\u0028\u0029",
            "name": "getTricks",
            "summary": "",
            "url": "classes/App-Entity-Video.html#method_getTricks"
        },                {
            "fqsen": "\\App\\Entity\\Video\u003A\u003AsetTricks\u0028\u0029",
            "name": "setTricks",
            "summary": "",
            "url": "classes/App-Entity-Video.html#method_setTricks"
        },                {
            "fqsen": "\\App\\Entity\\Video\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/App-Entity-Video.html#property_id"
        },                {
            "fqsen": "\\App\\Entity\\Video\u003A\u003A\u0024title",
            "name": "title",
            "summary": "",
            "url": "classes/App-Entity-Video.html#property_title"
        },                {
            "fqsen": "\\App\\Entity\\Video\u003A\u003A\u0024url",
            "name": "url",
            "summary": "",
            "url": "classes/App-Entity-Video.html#property_url"
        },                {
            "fqsen": "\\App\\Entity\\Video\u003A\u003A\u0024tricks",
            "name": "tricks",
            "summary": "",
            "url": "classes/App-Entity-Video.html#property_tricks"
        },                {
            "fqsen": "\\App\\Form\\AccountType",
            "name": "AccountType",
            "summary": "",
            "url": "classes/App-Form-AccountType.html"
        },                {
            "fqsen": "\\App\\Form\\AccountType\u003A\u003AbuildForm\u0028\u0029",
            "name": "buildForm",
            "summary": "",
            "url": "classes/App-Form-AccountType.html#method_buildForm"
        },                {
            "fqsen": "\\App\\Form\\AccountType\u003A\u003AconfigureOptions\u0028\u0029",
            "name": "configureOptions",
            "summary": "",
            "url": "classes/App-Form-AccountType.html#method_configureOptions"
        },                {
            "fqsen": "\\App\\Form\\AddTrickType",
            "name": "AddTrickType",
            "summary": "",
            "url": "classes/App-Form-AddTrickType.html"
        },                {
            "fqsen": "\\App\\Form\\AddTrickType\u003A\u003AsetConfigurationAttribute\u0028\u0029",
            "name": "setConfigurationAttribute",
            "summary": "Configures\u0020label\u0020input",
            "url": "classes/App-Form-AddTrickType.html#method_setConfigurationAttribute"
        },                {
            "fqsen": "\\App\\Form\\AddTrickType\u003A\u003AbuildForm\u0028\u0029",
            "name": "buildForm",
            "summary": "",
            "url": "classes/App-Form-AddTrickType.html#method_buildForm"
        },                {
            "fqsen": "\\App\\Form\\AddTrickType\u003A\u003AconfigureOptions\u0028\u0029",
            "name": "configureOptions",
            "summary": "",
            "url": "classes/App-Form-AddTrickType.html#method_configureOptions"
        },                {
            "fqsen": "\\App\\Form\\CommentType",
            "name": "CommentType",
            "summary": "",
            "url": "classes/App-Form-CommentType.html"
        },                {
            "fqsen": "\\App\\Form\\CommentType\u003A\u003AbuildForm\u0028\u0029",
            "name": "buildForm",
            "summary": "",
            "url": "classes/App-Form-CommentType.html#method_buildForm"
        },                {
            "fqsen": "\\App\\Form\\CommentType\u003A\u003AconfigureOptions\u0028\u0029",
            "name": "configureOptions",
            "summary": "",
            "url": "classes/App-Form-CommentType.html#method_configureOptions"
        },                {
            "fqsen": "\\App\\Form\\EditTrickType",
            "name": "EditTrickType",
            "summary": "",
            "url": "classes/App-Form-EditTrickType.html"
        },                {
            "fqsen": "\\App\\Form\\EditTrickType\u003A\u003AsetConfigurationAttribute\u0028\u0029",
            "name": "setConfigurationAttribute",
            "summary": "",
            "url": "classes/App-Form-EditTrickType.html#method_setConfigurationAttribute"
        },                {
            "fqsen": "\\App\\Form\\EditTrickType\u003A\u003AbuildForm\u0028\u0029",
            "name": "buildForm",
            "summary": "",
            "url": "classes/App-Form-EditTrickType.html#method_buildForm"
        },                {
            "fqsen": "\\App\\Form\\EditTrickType\u003A\u003AconfigureOptions\u0028\u0029",
            "name": "configureOptions",
            "summary": "",
            "url": "classes/App-Form-EditTrickType.html#method_configureOptions"
        },                {
            "fqsen": "\\App\\Form\\ForgotPasswordType",
            "name": "ForgotPasswordType",
            "summary": "",
            "url": "classes/App-Form-ForgotPasswordType.html"
        },                {
            "fqsen": "\\App\\Form\\ForgotPasswordType\u003A\u003AbuildForm\u0028\u0029",
            "name": "buildForm",
            "summary": "",
            "url": "classes/App-Form-ForgotPasswordType.html#method_buildForm"
        },                {
            "fqsen": "\\App\\Form\\ForgotPasswordType\u003A\u003AconfigureOptions\u0028\u0029",
            "name": "configureOptions",
            "summary": "",
            "url": "classes/App-Form-ForgotPasswordType.html#method_configureOptions"
        },                {
            "fqsen": "\\App\\Form\\PictureType",
            "name": "PictureType",
            "summary": "",
            "url": "classes/App-Form-PictureType.html"
        },                {
            "fqsen": "\\App\\Form\\PictureType\u003A\u003AbuildForm\u0028\u0029",
            "name": "buildForm",
            "summary": "",
            "url": "classes/App-Form-PictureType.html#method_buildForm"
        },                {
            "fqsen": "\\App\\Form\\PictureType\u003A\u003AconfigureOptions\u0028\u0029",
            "name": "configureOptions",
            "summary": "",
            "url": "classes/App-Form-PictureType.html#method_configureOptions"
        },                {
            "fqsen": "\\App\\Form\\RegistrationType",
            "name": "RegistrationType",
            "summary": "",
            "url": "classes/App-Form-RegistrationType.html"
        },                {
            "fqsen": "\\App\\Form\\RegistrationType\u003A\u003AsetConfigurationAttribute\u0028\u0029",
            "name": "setConfigurationAttribute",
            "summary": "Undocumented\u0020function",
            "url": "classes/App-Form-RegistrationType.html#method_setConfigurationAttribute"
        },                {
            "fqsen": "\\App\\Form\\RegistrationType\u003A\u003AbuildForm\u0028\u0029",
            "name": "buildForm",
            "summary": "",
            "url": "classes/App-Form-RegistrationType.html#method_buildForm"
        },                {
            "fqsen": "\\App\\Form\\RegistrationType\u003A\u003AconfigureOptions\u0028\u0029",
            "name": "configureOptions",
            "summary": "",
            "url": "classes/App-Form-RegistrationType.html#method_configureOptions"
        },                {
            "fqsen": "\\App\\Form\\ResetPasswordType",
            "name": "ResetPasswordType",
            "summary": "",
            "url": "classes/App-Form-ResetPasswordType.html"
        },                {
            "fqsen": "\\App\\Form\\ResetPasswordType\u003A\u003AbuildForm\u0028\u0029",
            "name": "buildForm",
            "summary": "",
            "url": "classes/App-Form-ResetPasswordType.html#method_buildForm"
        },                {
            "fqsen": "\\App\\Form\\ResetPasswordType\u003A\u003AconfigureOptions\u0028\u0029",
            "name": "configureOptions",
            "summary": "",
            "url": "classes/App-Form-ResetPasswordType.html#method_configureOptions"
        },                {
            "fqsen": "\\App\\Form\\VideoType",
            "name": "VideoType",
            "summary": "",
            "url": "classes/App-Form-VideoType.html"
        },                {
            "fqsen": "\\App\\Form\\VideoType\u003A\u003AsetConfigurationAttribute\u0028\u0029",
            "name": "setConfigurationAttribute",
            "summary": "",
            "url": "classes/App-Form-VideoType.html#method_setConfigurationAttribute"
        },                {
            "fqsen": "\\App\\Form\\VideoType\u003A\u003AbuildForm\u0028\u0029",
            "name": "buildForm",
            "summary": "",
            "url": "classes/App-Form-VideoType.html#method_buildForm"
        },                {
            "fqsen": "\\App\\Form\\VideoType\u003A\u003AconfigureOptions\u0028\u0029",
            "name": "configureOptions",
            "summary": "",
            "url": "classes/App-Form-VideoType.html#method_configureOptions"
        },                {
            "fqsen": "\\App\\Kernel",
            "name": "Kernel",
            "summary": "",
            "url": "classes/App-Kernel.html"
        },                {
            "fqsen": "\\App\\Kernel\u003A\u003AconfigureContainer\u0028\u0029",
            "name": "configureContainer",
            "summary": "",
            "url": "classes/App-Kernel.html#method_configureContainer"
        },                {
            "fqsen": "\\App\\Kernel\u003A\u003AconfigureRoutes\u0028\u0029",
            "name": "configureRoutes",
            "summary": "",
            "url": "classes/App-Kernel.html#method_configureRoutes"
        },                {
            "fqsen": "\\App\\Repository\\CategoryRepository",
            "name": "CategoryRepository",
            "summary": "",
            "url": "classes/App-Repository-CategoryRepository.html"
        },                {
            "fqsen": "\\App\\Repository\\CategoryRepository\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Repository-CategoryRepository.html#method___construct"
        },                {
            "fqsen": "\\App\\Repository\\CommentRepository",
            "name": "CommentRepository",
            "summary": "",
            "url": "classes/App-Repository-CommentRepository.html"
        },                {
            "fqsen": "\\App\\Repository\\CommentRepository\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Repository-CommentRepository.html#method___construct"
        },                {
            "fqsen": "\\App\\Repository\\PasswordUpdateRepository",
            "name": "PasswordUpdateRepository",
            "summary": "",
            "url": "classes/App-Repository-PasswordUpdateRepository.html"
        },                {
            "fqsen": "\\App\\Repository\\PasswordUpdateRepository\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Repository-PasswordUpdateRepository.html#method___construct"
        },                {
            "fqsen": "\\App\\Repository\\PictureRepository",
            "name": "PictureRepository",
            "summary": "",
            "url": "classes/App-Repository-PictureRepository.html"
        },                {
            "fqsen": "\\App\\Repository\\PictureRepository\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Repository-PictureRepository.html#method___construct"
        },                {
            "fqsen": "\\App\\Repository\\TrickRepository",
            "name": "TrickRepository",
            "summary": "",
            "url": "classes/App-Repository-TrickRepository.html"
        },                {
            "fqsen": "\\App\\Repository\\TrickRepository\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Repository-TrickRepository.html#method___construct"
        },                {
            "fqsen": "\\App\\Repository\\TrickRepository\u003A\u003AfindOneById\u0028\u0029",
            "name": "findOneById",
            "summary": "",
            "url": "classes/App-Repository-TrickRepository.html#method_findOneById"
        },                {
            "fqsen": "\\App\\Repository\\UserRepository",
            "name": "UserRepository",
            "summary": "",
            "url": "classes/App-Repository-UserRepository.html"
        },                {
            "fqsen": "\\App\\Repository\\UserRepository\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Repository-UserRepository.html#method___construct"
        },                {
            "fqsen": "\\App\\Repository\\VideoRepository",
            "name": "VideoRepository",
            "summary": "",
            "url": "classes/App-Repository-VideoRepository.html"
        },                {
            "fqsen": "\\App\\Repository\\VideoRepository\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Repository-VideoRepository.html#method___construct"
        },                {
            "fqsen": "\\App\\Security\\LoginFormAuthenticator",
            "name": "LoginFormAuthenticator",
            "summary": "",
            "url": "classes/App-Security-LoginFormAuthenticator.html"
        },                {
            "fqsen": "\\App\\Security\\LoginFormAuthenticator\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Security-LoginFormAuthenticator.html#method___construct"
        },                {
            "fqsen": "\\App\\Security\\LoginFormAuthenticator\u003A\u003Asupports\u0028\u0029",
            "name": "supports",
            "summary": "",
            "url": "classes/App-Security-LoginFormAuthenticator.html#method_supports"
        },                {
            "fqsen": "\\App\\Security\\LoginFormAuthenticator\u003A\u003AgetCredentials\u0028\u0029",
            "name": "getCredentials",
            "summary": "",
            "url": "classes/App-Security-LoginFormAuthenticator.html#method_getCredentials"
        },                {
            "fqsen": "\\App\\Security\\LoginFormAuthenticator\u003A\u003AgetUser\u0028\u0029",
            "name": "getUser",
            "summary": "",
            "url": "classes/App-Security-LoginFormAuthenticator.html#method_getUser"
        },                {
            "fqsen": "\\App\\Security\\LoginFormAuthenticator\u003A\u003AcheckCredentials\u0028\u0029",
            "name": "checkCredentials",
            "summary": "",
            "url": "classes/App-Security-LoginFormAuthenticator.html#method_checkCredentials"
        },                {
            "fqsen": "\\App\\Security\\LoginFormAuthenticator\u003A\u003AgetPassword\u0028\u0029",
            "name": "getPassword",
            "summary": "Used\u0020to\u0020upgrade\u0020\u0028rehash\u0029\u0020the\u0020user\u0027s\u0020password\u0020automatically\u0020over\u0020time.",
            "url": "classes/App-Security-LoginFormAuthenticator.html#method_getPassword"
        },                {
            "fqsen": "\\App\\Security\\LoginFormAuthenticator\u003A\u003AonAuthenticationSuccess\u0028\u0029",
            "name": "onAuthenticationSuccess",
            "summary": "",
            "url": "classes/App-Security-LoginFormAuthenticator.html#method_onAuthenticationSuccess"
        },                {
            "fqsen": "\\App\\Security\\LoginFormAuthenticator\u003A\u003AgetLoginUrl\u0028\u0029",
            "name": "getLoginUrl",
            "summary": "",
            "url": "classes/App-Security-LoginFormAuthenticator.html#method_getLoginUrl"
        },                {
            "fqsen": "\\App\\Security\\LoginFormAuthenticator\u003A\u003ALOGIN_ROUTE",
            "name": "LOGIN_ROUTE",
            "summary": "",
            "url": "classes/App-Security-LoginFormAuthenticator.html#constant_LOGIN_ROUTE"
        },                {
            "fqsen": "\\App\\Security\\LoginFormAuthenticator\u003A\u003A\u0024entityManager",
            "name": "entityManager",
            "summary": "",
            "url": "classes/App-Security-LoginFormAuthenticator.html#property_entityManager"
        },                {
            "fqsen": "\\App\\Security\\LoginFormAuthenticator\u003A\u003A\u0024urlGenerator",
            "name": "urlGenerator",
            "summary": "",
            "url": "classes/App-Security-LoginFormAuthenticator.html#property_urlGenerator"
        },                {
            "fqsen": "\\App\\Security\\LoginFormAuthenticator\u003A\u003A\u0024csrfTokenManager",
            "name": "csrfTokenManager",
            "summary": "",
            "url": "classes/App-Security-LoginFormAuthenticator.html#property_csrfTokenManager"
        },                {
            "fqsen": "\\App\\Security\\LoginFormAuthenticator\u003A\u003A\u0024passwordEncoder",
            "name": "passwordEncoder",
            "summary": "",
            "url": "classes/App-Security-LoginFormAuthenticator.html#property_passwordEncoder"
        },                {
            "fqsen": "\\App\\Service\\Mail",
            "name": "Mail",
            "summary": "",
            "url": "classes/App-Service-Mail.html"
        },                {
            "fqsen": "\\App\\Service\\Mail\u003A\u003AmailFormat\u0028\u0029",
            "name": "mailFormat",
            "summary": "",
            "url": "classes/App-Service-Mail.html#method_mailFormat"
        },                {
            "fqsen": "\\App\\Service\\Paginator",
            "name": "Paginator",
            "summary": "",
            "url": "classes/App-Service-Paginator.html"
        },                {
            "fqsen": "\\App\\Service\\Paginator\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Service-Paginator.html#method___construct"
        },                {
            "fqsen": "\\App\\Service\\Paginator\u003A\u003AgetPages\u0028\u0029",
            "name": "getPages",
            "summary": "",
            "url": "classes/App-Service-Paginator.html#method_getPages"
        },                {
            "fqsen": "\\App\\Service\\Paginator\u003A\u003AgetData\u0028\u0029",
            "name": "getData",
            "summary": "",
            "url": "classes/App-Service-Paginator.html#method_getData"
        },                {
            "fqsen": "\\App\\Service\\Paginator\u003A\u003AsetEntityClass\u0028\u0029",
            "name": "setEntityClass",
            "summary": "",
            "url": "classes/App-Service-Paginator.html#method_setEntityClass"
        },                {
            "fqsen": "\\App\\Service\\Paginator\u003A\u003AgetEntityClass\u0028\u0029",
            "name": "getEntityClass",
            "summary": "",
            "url": "classes/App-Service-Paginator.html#method_getEntityClass"
        },                {
            "fqsen": "\\App\\Service\\Paginator\u003A\u003AsetLimit\u0028\u0029",
            "name": "setLimit",
            "summary": "",
            "url": "classes/App-Service-Paginator.html#method_setLimit"
        },                {
            "fqsen": "\\App\\Service\\Paginator\u003A\u003AgetLimit\u0028\u0029",
            "name": "getLimit",
            "summary": "",
            "url": "classes/App-Service-Paginator.html#method_getLimit"
        },                {
            "fqsen": "\\App\\Service\\Paginator\u003A\u003AsetPage\u0028\u0029",
            "name": "setPage",
            "summary": "",
            "url": "classes/App-Service-Paginator.html#method_setPage"
        },                {
            "fqsen": "\\App\\Service\\Paginator\u003A\u003AgetPage\u0028\u0029",
            "name": "getPage",
            "summary": "",
            "url": "classes/App-Service-Paginator.html#method_getPage"
        },                {
            "fqsen": "\\App\\Service\\Paginator\u003A\u003AsetOrderBy\u0028\u0029",
            "name": "setOrderBy",
            "summary": "",
            "url": "classes/App-Service-Paginator.html#method_setOrderBy"
        },                {
            "fqsen": "\\App\\Service\\Paginator\u003A\u003AgetOrderBy\u0028\u0029",
            "name": "getOrderBy",
            "summary": "",
            "url": "classes/App-Service-Paginator.html#method_getOrderBy"
        },                {
            "fqsen": "\\App\\Service\\Paginator\u003A\u003A\u0024entityClass",
            "name": "entityClass",
            "summary": "",
            "url": "classes/App-Service-Paginator.html#property_entityClass"
        },                {
            "fqsen": "\\App\\Service\\Paginator\u003A\u003A\u0024limit",
            "name": "limit",
            "summary": "",
            "url": "classes/App-Service-Paginator.html#property_limit"
        },                {
            "fqsen": "\\App\\Service\\Paginator\u003A\u003A\u0024page",
            "name": "page",
            "summary": "",
            "url": "classes/App-Service-Paginator.html#property_page"
        },                {
            "fqsen": "\\App\\Service\\Paginator\u003A\u003A\u0024manager",
            "name": "manager",
            "summary": "",
            "url": "classes/App-Service-Paginator.html#property_manager"
        },                {
            "fqsen": "\\App\\Service\\Paginator\u003A\u003A\u0024orderBy",
            "name": "orderBy",
            "summary": "",
            "url": "classes/App-Service-Paginator.html#property_orderBy"
        },                {
            "fqsen": "\\App\\Service\\FileUploader",
            "name": "FileUploader",
            "summary": "",
            "url": "classes/App-Service-FileUploader.html"
        },                {
            "fqsen": "\\App\\Service\\FileUploader\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Service-FileUploader.html#method___construct"
        },                {
            "fqsen": "\\App\\Service\\FileUploader\u003A\u003Aupload\u0028\u0029",
            "name": "upload",
            "summary": "Rename\u0020file\u0020uploaded\u0020and\u0020move\u0020them\u0020in\u0020Picture_Directory",
            "url": "classes/App-Service-FileUploader.html#method_upload"
        },                {
            "fqsen": "\\App\\Service\\FileUploader\u003A\u003AgetTargetDirectory\u0028\u0029",
            "name": "getTargetDirectory",
            "summary": "",
            "url": "classes/App-Service-FileUploader.html#method_getTargetDirectory"
        },                {
            "fqsen": "\\App\\Service\\FileUploader\u003A\u003A\u0024targetDirectory",
            "name": "targetDirectory",
            "summary": "",
            "url": "classes/App-Service-FileUploader.html#property_targetDirectory"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\App\\Controller",
            "name": "Controller",
            "summary": "",
            "url": "namespaces/app-controller.html"
        },                {
            "fqsen": "\\App\\DataFixtures",
            "name": "DataFixtures",
            "summary": "",
            "url": "namespaces/app-datafixtures.html"
        },                {
            "fqsen": "\\App\\Entity",
            "name": "Entity",
            "summary": "",
            "url": "namespaces/app-entity.html"
        },                {
            "fqsen": "\\App\\Form",
            "name": "Form",
            "summary": "",
            "url": "namespaces/app-form.html"
        },                {
            "fqsen": "\\App",
            "name": "App",
            "summary": "",
            "url": "namespaces/app.html"
        },                {
            "fqsen": "\\App\\Repository",
            "name": "Repository",
            "summary": "",
            "url": "namespaces/app-repository.html"
        },                {
            "fqsen": "\\App\\Security",
            "name": "Security",
            "summary": "",
            "url": "namespaces/app-security.html"
        },                {
            "fqsen": "\\App\\Service",
            "name": "Service",
            "summary": "",
            "url": "namespaces/app-service.html"
        }            ]
);
